### PR TITLE
Letterplace Mini Release

### PR DESCRIPTION
**Pull request by kabouzeid**
Clean up documentation for fpadim.lib and fpaprops.lib
Add fpalgebras.lib

Add lpDivision()
Add lpPrint()
Add lpIsShiftInvariant()

Modification to the Letterplace Ring

Fix bug in lpShift()
Fix bug in lpSubstitute()
Fix bug in lpNF()
Fix bug in lpReduce()

### CODE REVIEW

**Comment by hannes14** [comment]
should also include changed tests

**Comment by kabouzeid** [comment]
I don't know how to create the .res.gz.uu files

**Comment by hannes14** [comment]
see Tst/README for testing and generating new tests/new results

**Comment by hannes14** [comment]
testing the examples results in errors for:
- example crystallographicGroupP2GG
- example crystallographicGroupP31M
- example crystallographicGroupP6
- example crystallographicGroupP6MM
see http://www.mathematik.uni-kl.de/~hannes/s/sing_635.htm

**Pull request merged**
